/* empty css                      */import{S as l,N as h,A as a}from"./assets/vendor-B982kwEF.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const g=[{selector:".game-swiper",slideClass:"game-swiper-slide",wrapperClass:"game-swiper-wrapper",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"}}],c={};function u(){const s=window.innerWidth;g.forEach(o=>{const r=document.querySelector(o.selector);if(!r)return;const n=o.selector;if(c[n]&&(c[n].destroy(!0,!0),delete c[n]),o.selector===".game-swiper"&&s<1439){const e=new l(r,{modules:[h],slidesPerView:1,spaceBetween:10,loop:!0,slideClass:o.slideClass,wrapperClass:o.wrapperClass,direction:"horizontal",navigation:o.navigation});c[n]=e}})}function y(){const s=document.querySelector(".reviews-swiper-one"),o=document.querySelector(".reviews-swiper-two");s&&new l(s,{modules:[a],loop:!0,spaceBetween:20,speed:6e3,autoplay:{delay:0,disableOnInteraction:!1},breakpoints:{0:{slidesPerView:1},1439:{slidesPerView:2.5}}}),o&&new l(o,{modules:[a],loop:!0,spaceBetween:20,speed:7e3,autoplay:{delay:1,disableOnInteraction:!1,reverseDirection:!0},breakpoints:{0:{slidesPerView:1.2},1439:{slidesPerView:2}}})}document.addEventListener("DOMContentLoaded",()=>{u(),y()});window.addEventListener("resize",()=>{clearTimeout(window._swiperResizeTimeout),window._swiperResizeTimeout=setTimeout(u,300)});document.addEventListener("DOMContentLoaded",()=>{function s(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const e=document.getElementById(n);if(!e)return;const t=s(),i=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(n=>{n.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const i=t.substring(1);o(i)})});const r=window.location.hash;if(r){const n=r.substring(1);setTimeout(()=>{o(n)},1e3)}});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),o=s.querySelector(".icon"),r=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="36" height="30" viewBox="0 0 36 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M32 9L12 9" stroke="white" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M32 15L5 15" stroke="white" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M32 21L12 21" stroke="white" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,p=`
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M25 11L11 25M11 11L25 25" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,o.innerHTML=t?p:i,t?w():d()}),n.forEach(f=>f.addEventListener("click",()=>{d(),o.innerHTML=i,t=!1})),window.addEventListener("scroll",m);function w(){r.style.display="block"}function d(){r.style.display="none"}function m(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
